### ISSUE TITLE
Image upload fails when compiled

### ISSUE THREAD

**Issue by Codom** [isenseDev/AppVis#3]
The image upload works inside of the companion app. When it is compiled and installed onto the phone, the image upload feature causes the compiled version of the users application to crash.

**Comment by Codom** [comment]
Tested on here: https://drive.google.com/open?id=1XljLWgkFDGvI-Vr6w62CHuHISsxXkd8K
When compiled it fails suddenly upon any image upload.

**Comment by Codom** [comment]
New log output after altering permissions: Still doesn't work.
```'E/AndroidRuntime( 9546): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 9546): Process: appinventor.ai_Christopher_R_Odom.ISense_Unit_Tests_checkpoint1, PID: 9546
E/AndroidRuntime( 9546): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 9546): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime( 9546): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 9546): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 9546): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 9546): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 9546): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 9546): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime( 9546): Caused by: java.lang.NoClassDefFoundError: org.apache.http.entity.mime.MultipartEntityBuilder
E/AndroidRuntime( 9546): 	at edu.uml.cs.isense.api.API.uploadMedia(API.java:961)
E/AndroidRuntime( 9546): 	at edu.uml.cs.isense.iSENSEPublisher$UploadTask.doInBackground(iSENSEPublisher.java:526)
E/AndroidRuntime( 9546): 	at edu.uml.cs.isense.iSENSEPublisher$UploadTask.doInBackground(iSENSEPublisher.java:426)
E/AndroidRuntime( 9546): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime( 9546): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 9546): 	... 3 more
```

**Comment by Codom** [comment]
As the backtrace suggests, the issue is caused by the MultipartEntitiyBuilder class in the API file. The repo version of the isense api doesn't seem to match the one packaged inside of AppVis, which complicates things....
However, the source code is located inside of `appinventor/lib/isense/isenseapi-1.0.src.jar`
